spring:
  profiles:
    active: dev

---
server:
  port: 8181
spring:
  profiles: dev
  application:
    name: springcloud-provider01

eureka:
  client:
    serviceUrl: # 服务注册地址
      defaultZone: http://eureka.server.center8080:8080/eureka/,http://eureka.server.center8078:8078/eureka/,http://eureka.server.center8079:8079/eureka/


---
server:
  port: 8281
spring:
  profiles: test
  application:
    name: springcloud-provider01

  eureka:
    client:
      serviceUrl: # 服务注册地址
        defaultZone: http://eureka.server.center8080:8080/eureka/,http://eureka.server.center8078:8078/eureka/,http://eureka.server.center8079:8079/eureka/


